# Generated by Django 3.1.1 on 2020-09-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
